// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetPythonPath():Promise<string>;

export function RunNuclei(arg1:string,arg2:string):Promise<string>;

export function RunPython(arg1:string):Promise<string>;

export function SetPythonPath(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
