// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPythonPath() {
  return window['go']['poc']['PocService']['GetPythonPath']();
}

export function RunNuclei(arg1, arg2) {
  return window['go']['poc']['PocService']['RunNuclei'](arg1, arg2);
}

export function RunPython(arg1) {
  return window['go']['poc']['PocService']['RunPython'](arg1);
}

export function SetPythonPath(arg1) {
  return window['go']['poc']['PocService']['SetPythonPath'](arg1);
}

export function Startup(arg1) {
  return window['go']['poc']['PocService']['Startup'](arg1);
}
