// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {context} from '../models';

export function GetAsset(arg1:number):Promise<db.Asset>;

export function GetAssetAuthResults(arg1:number):Promise<Array<db.AuthResult>>;

export function GetAssetPorts(arg1:number):Promise<Array<db.AssetPort>>;

export function GetAssetSensitiveResults(arg1:number):Promise<Array<db.SensitiveResult>>;

export function GetAssetWebDirectories(arg1:number):Promise<Array<db.WebDirectory>>;

export function GetAssetWebJSFiles(arg1:number):Promise<Array<db.WebJSFile>>;

export function GetAssets():Promise<Array<db.Asset>>;

export function GetWebDirectories(arg1:number):Promise<Array<db.WebDirectory>>;

export function GetWebJSFiles(arg1:number):Promise<Array<db.WebJSFile>>;

export function GetWebServices(arg1:number):Promise<Array<db.WebService>>;

export function Startup(arg1:context.Context):Promise<void>;
