// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAsset(arg1) {
  return window['go']['infogather']['AssetService']['GetAsset'](arg1);
}

export function GetAssetAuthResults(arg1) {
  return window['go']['infogather']['AssetService']['GetAssetAuthResults'](arg1);
}

export function GetAssetPorts(arg1) {
  return window['go']['infogather']['AssetService']['GetAssetPorts'](arg1);
}

export function GetAssetSensitiveResults(arg1) {
  return window['go']['infogather']['AssetService']['GetAssetSensitiveResults'](arg1);
}

export function GetAssetWebDirectories(arg1) {
  return window['go']['infogather']['AssetService']['GetAssetWebDirectories'](arg1);
}

export function GetAssetWebJSFiles(arg1) {
  return window['go']['infogather']['AssetService']['GetAssetWebJSFiles'](arg1);
}

export function GetAssets() {
  return window['go']['infogather']['AssetService']['GetAssets']();
}

export function GetWebDirectories(arg1) {
  return window['go']['infogather']['AssetService']['GetWebDirectories'](arg1);
}

export function GetWebJSFiles(arg1) {
  return window['go']['infogather']['AssetService']['GetWebJSFiles'](arg1);
}

export function GetWebServices(arg1) {
  return window['go']['infogather']['AssetService']['GetWebServices'](arg1);
}

export function Startup(arg1) {
  return window['go']['infogather']['AssetService']['Startup'](arg1);
}
