// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {infogather} from '../models';
import {context} from '../models';

export function AddTarget(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function ClearTargets():Promise<void>;

export function GetDictionaries():Promise<Array<infogather.Dictionary>>;

export function GetTargets():Promise<Array<infogather.BruteForceTarget>>;

export function SelectDictionaryFile():Promise<string>;

export function StartAttack(arg1:infogather.BruteForceConfig):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAttack():Promise<void>;
