// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1, arg2, arg3, arg4) {
  return window['go']['infogather']['BruteForceService']['AddTarget'](arg1, arg2, arg3, arg4);
}

export function ClearTargets() {
  return window['go']['infogather']['BruteForceService']['ClearTargets']();
}

export function GetDictionaries() {
  return window['go']['infogather']['BruteForceService']['GetDictionaries']();
}

export function GetTargets() {
  return window['go']['infogather']['BruteForceService']['GetTargets']();
}

export function SelectDictionaryFile() {
  return window['go']['infogather']['BruteForceService']['SelectDictionaryFile']();
}

export function StartAttack(arg1) {
  return window['go']['infogather']['BruteForceService']['StartAttack'](arg1);
}

export function Startup(arg1) {
  return window['go']['infogather']['BruteForceService']['Startup'](arg1);
}

export function StopAttack() {
  return window['go']['infogather']['BruteForceService']['StopAttack']();
}
