// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {infogather} from '../models';
import {context} from '../models';

export function AddInfo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearData():Promise<void>;

export function GetDictionaries():Promise<Array<infogather.Dictionary>>;

export function GetDirScanResultModel():Promise<infogather.DirScanResult>;

export function ListInfo():Promise<Array<infogather.InfoGathering>>;

export function PauseScan(arg1:boolean):Promise<void>;

export function SelectDictionaryFile():Promise<string>;

export function StartDirScan(arg1:infogather.DirScanConfig):Promise<void>;

export function StartScan(arg1:infogather.ScanConfig):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopScan():Promise<void>;
