// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInfo(arg1, arg2, arg3) {
  return window['go']['infogather']['InfoService']['AddInfo'](arg1, arg2, arg3);
}

export function ClearData() {
  return window['go']['infogather']['InfoService']['ClearData']();
}

export function GetDictionaries() {
  return window['go']['infogather']['InfoService']['GetDictionaries']();
}

export function GetDirScanResultModel() {
  return window['go']['infogather']['InfoService']['GetDirScanResultModel']();
}

export function ListInfo() {
  return window['go']['infogather']['InfoService']['ListInfo']();
}

export function PauseScan(arg1) {
  return window['go']['infogather']['InfoService']['PauseScan'](arg1);
}

export function SelectDictionaryFile() {
  return window['go']['infogather']['InfoService']['SelectDictionaryFile']();
}

export function StartDirScan(arg1) {
  return window['go']['infogather']['InfoService']['StartDirScan'](arg1);
}

export function StartScan(arg1) {
  return window['go']['infogather']['InfoService']['StartScan'](arg1);
}

export function Startup(arg1) {
  return window['go']['infogather']['InfoService']['Startup'](arg1);
}

export function StopScan() {
  return window['go']['infogather']['InfoService']['StopScan']();
}
