// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindJS(arg1, arg2) {
  return window['go']['infogather']['JSFinderService']['FindJS'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['infogather']['JSFinderService']['Startup'](arg1);
}
