// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {infogather} from '../models';
import {context} from '../models';

export function FindJS(arg1:string,arg2:infogather.JSFinderOptions):Promise<infogather.JSFindResult>;

export function Startup(arg1:context.Context):Promise<void>;
