// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVuln(arg1) {
  return window['go']['vuln']['VulnService']['AddVuln'](arg1);
}

export function DeleteVuln(arg1) {
  return window['go']['vuln']['VulnService']['DeleteVuln'](arg1);
}

export function ListVulns() {
  return window['go']['vuln']['VulnService']['ListVulns']();
}

export function SearchVulns(arg1) {
  return window['go']['vuln']['VulnService']['SearchVulns'](arg1);
}

export function Startup(arg1) {
  return window['go']['vuln']['VulnService']['Startup'](arg1);
}

export function UpdateVuln(arg1) {
  return window['go']['vuln']['VulnService']['UpdateVuln'](arg1);
}

export function VerifyVuln(arg1, arg2) {
  return window['go']['vuln']['VulnService']['VerifyVuln'](arg1, arg2);
}
