// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vuln} from '../models';
import {context} from '../models';

export function AddVuln(arg1:vuln.Vulnerability):Promise<void>;

export function DeleteVuln(arg1:number):Promise<void>;

export function ListVulns():Promise<Array<vuln.Vulnerability>>;

export function SearchVulns(arg1:string):Promise<Array<vuln.Vulnerability>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateVuln(arg1:vuln.Vulnerability):Promise<void>;

export function VerifyVuln(arg1:number,arg2:string):Promise<string>;
