// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListLogFiles() {
  return window['go']['logs']['LogService']['ListLogFiles']();
}

export function ReadLogFile(arg1) {
  return window['go']['logs']['LogService']['ReadLogFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['logs']['LogService']['Startup'](arg1);
}
