// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';
import {context} from '../models';

export function ListLogFiles():Promise<Array<logs.LogFile>>;

export function ReadLogFile(arg1:string):Promise<Array<string>>;

export function Startup(arg1:context.Context):Promise<void>;
